# Generated by Django 3.1.3 on 2021-07-27 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaybackSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal', models.IntegerField(choices=[(5000, 'Option 1'), (10000, 'Option 2'), (20000, 'Option 3'), (50000, 'Option 4'), (100000, 'Option 5'), (200000, 'Option 6'), (300000, 'Option 7'), (400000, 'Option 8'), (500000, 'Option 9'), (1000000, 'Option 10'), (1500000, 'Option 11'), (2000000, 'Option 12'), (2500000, 'Option 13'), (3000000, 'Option 14'), (3500000, 'Option 15'), (4000000, 'Option 16'), (4500000, 'Option 17'), (5000000, 'Option 18'), (6000000, 'Option 19'), (7000000, 'Option 20'), (8000000, 'Option 21'), (9000000, 'Option 22'), (10000000, 'Option 23')])),
                ('interest', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('commission', models.IntegerField()),
                ('payback_round', models.IntegerField()),
                ('payback_date', models.DateField()),
            ],
            options={
                'db_table': 'debtor_paybacks',
            },
        ),
        migrations.CreateModel(
            name='UserDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('deal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deals.deal')),
            ],
            options={
                'db_table': 'users_deals',
            },
        ),
        migrations.CreateModel(
            name='UserPayback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal', models.IntegerField()),
                ('interest', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('commission', models.IntegerField()),
                ('payback_round', models.IntegerField()),
                ('state', models.IntegerField(choices=[(1, '지급예정'), (2, '지급완료'), (3, '미지급')])),
                ('payback_date', models.DateField()),
                ('users_deals', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investments.userdeal')),
            ],
            options={
                'db_table': 'user_paybacks',
            },
        ),
    ]
