# Generated by Django 3.2.5 on 2021-07-20 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('earning_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('repayment_period', models.IntegerField()),
                ('net_amount', models.IntegerField()),
                ('repayment_day', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('reason', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deals.category')),
            ],
            options={
                'db_table': 'deals',
            },
        ),
        migrations.CreateModel(
            name='DealGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'deal_grades',
            },
        ),
        migrations.CreateModel(
            name='DealStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'deal_statuses',
            },
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
            ],
            options={
                'db_table': 'debtors',
            },
        ),
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ltv_ratio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('appraised_value', models.IntegerField()),
                ('senior_loan_amount', models.IntegerField()),
                ('address', models.TextField()),
                ('completed_date', models.DateField()),
                ('scale', models.CharField(max_length=100)),
                ('supply_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('using_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('floors', models.CharField(max_length=100)),
                ('is_usage', models.BooleanField()),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.deal')),
            ],
            options={
                'db_table': 'mortgages',
            },
        ),
        migrations.CreateModel(
            name='RepaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'repayment_methods',
            },
        ),
        migrations.CreateModel(
            name='SellingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'selling_points',
            },
        ),
        migrations.CreateModel(
            name='MortgageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500)),
                ('mortgage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.mortgage')),
            ],
            options={
                'db_table': 'mortgage_images',
            },
        ),
        migrations.AddField(
            model_name='mortgage',
            name='selling_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deals.sellingpoint'),
        ),
        migrations.AddField(
            model_name='deal',
            name='deal_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deals.dealstatus'),
        ),
        migrations.AddField(
            model_name='deal',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deals.debtor'),
        ),
        migrations.AddField(
            model_name='deal',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deals.dealgrade'),
        ),
        migrations.AddField(
            model_name='deal',
            name='repayment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deals.repaymentmethod'),
        ),
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField()),
                ('credit_date', models.DateField()),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.debtor')),
            ],
            options={
                'db_table': 'credit_scores',
            },
        ),
    ]
