# Generated by Django 3.2.5 on 2021-07-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealstatus',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
